# Generated by Django 4.2.6 on 2023-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('baby food', 'baby food'), ('breads', 'breads'), ('drinks', 'drinks'), ('fruits', 'fruits'), ('meat', 'meat'), ('ready meal', 'ready meal'), ('vegetables', 'vegetables')], max_length=20),
        ),
    ]
