# Generated by Django 4.2.6 on 2023-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('babyfood', 'baby food'), ('breads', 'breads'), ('drinks', 'drinks'), ('fruits', 'fruits'), ('meat', 'meat'), ('readymeal', 'ready meal'), ('vegetables', 'vegetables')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
