# Generated by Django 4.2.6 on 2023-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_payment_amount_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
